Fix(cicd):  docker build and deploy stage

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -125,34 +125,78 @@ jobs:
 
 
 # ---------------- DEPLOY ----------------
-  deploy:
-    needs: integration
-    runs-on: ubuntu-latest
-    if: github.ref == 'refs/heads/main'
+deploy:
+  needs: integration
+  runs-on: ubuntu-latest
+  if: github.ref == 'refs/heads/main'
 
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4 
+  steps:
+    - name: Checkout code
+      uses: actions/checkout@v4 
 
-      - name: Build API image
-        run: docker build -t api:${{ github.sha }} api
+    - name: Build API image
+      run: docker build -t api:${{ github.sha }} api
 
-      - name: Remove old container
-        run: |
-          docker stop api || true
-          docker rm api || true
+    # 🚀 START NEW CONTAINER (DO NOT TOUCH OLD)
+    - name: Start new container
+      run: docker run -d --name api_new -p 8080:8000 api:${{ github.sha }}
 
-      - name: Run container
-        run: |
-          docker run -d --name api -p 80:8000 api:${{ github.sha }}
+    # 🩺 HEALTH CHECK (MAX 60s)
+    - name: Health check new container
+      run: |
+        echo "Checking new container health..."
+        for i in {1..12}; do
+          if curl -f http://localhost:8080/health; then
+            echo "New container is healthy"
+            exit 0
+          fi
+          sleep 5
+        done
+        echo "Health check failed"
+        docker logs api_new
+        docker rm -f api_new
+        exit 1
 
-      - name: Health check
-        run: |
-          echo "Checking application..."
-          for i in {1..12}; do
-            curl -f http://localhost:80/health && exit 0
-            sleep 5
-          done
+    # 🔄 SWITCH TRAFFIC
+    - name: Replace old container
+      run: |
+        docker stop api || true
+        docker rm api || true
+        docker rename api_new api
+  
+  
+  
+  
+  
+  
+  # deploy:
+  #   needs: integration
+  #   runs-on: ubuntu-latest
+  #   if: github.ref == 'refs/heads/main'
+
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4 
+
+  #     - name: Build API image
+  #       run: docker build -t api:${{ github.sha }} api
+
+  #     - name: Remove old container
+  #       run: |
+  #         docker stop api || true
+  #         docker rm api || true
+
+  #     - name: Run container
+  #       run: |
+  #         docker run -d --name api -p 80:8000 api:${{ github.sha }}
+
+  #     - name: Health check
+  #       run: |
+  #         echo "Checking application..."
+  #         for i in {1..12}; do
+  #           curl -f http://localhost:80/health && exit 0
+  #           sleep 5
+  #         done
 
 
 
